### ISSUE TITLE
RegEx error

### ISSUE THREAD

**Issue by q3fuba** [blunderboy/requestly#45] opened 2015-03-24 06:46 UTC
hi,
it looks you implemented RegEx does not accept any real Regular Expressions.

For Exaple it does not accpt `/example-(.*)` but it do `/example-(.*)/ig` ?!?
Also this is not allowed `.*/example-(.*)/ig` but it's a working RegEx in Java.

So any RegEx need to have a word after the group, but WHY?

So the RegEx `^.*/example-(.*)/.*$` with test Text `http://www.test.ocm/example-test/done` have to return `test` but Requestly returns `^.*/example-(.*)/.*$" is not a valid regular expression`

[link to Google!](http://google.com)

Edit:
Tested with http://www.regexplanet.com, http://myregexp.com and [RegexBuddy](http://www.regexbuddy.com)

**Comment by blunderboy** [comment] 2015-03-24 12:18
@q3fuba Thanks for reporting the issue. 
Actually, I intended to handle some simple cases for Regular Expression when I built the feature. 
You can take a look at this [file][0]. This is how I have tested if a regular expression is valid or not. 
I assumed every regular expression starts with `/` (Forward Slash) and ends with `/` again followed by the flags.

Do you mind submitting a PR for the fix. Its totally fine if you don't want to.

[0]: https://github.com/blunderboy/requestly/blob/27d272df70c6c4f2787384d178e2e4c12d6211eb/src/Shared/utils.js#L4

**Comment by blunderboy** [comment] 2015-03-27 13:14
@q3fuba No issues I will work towards fixing this problem. I have assigned this to me.

**Comment by blunderboy** [comment] 2015-03-28 06:23
@q3fuba Thanks for opening this. Based on above explanation I am closing this as it is "Working as Designed".

**Closed by blunderboy** 2015-03-28 06:23 UTC

**Comment by q3fuba** [comment] 2015-03-28 08:37
Mhm, but if `.*/example-(.*)/ig` is NOT a valid RegEx, why "any" RegEx Testing Site (which is Java RegEx) and Program (like Regexbuddy with Java Pattern) as well as Pascal RegEx and Visaul Basic .Net RegEx say IT IS valid?

Well i dont really care now becasue i found another Extension which work with my and any other RegEx i've tested with, your words "non valid RegEx" and it works ;)
