### ISSUE TITLE
Requestly should ignore the parameter if its empty

### ISSUE THREAD

**Issue by offhub** [blunderboy/requestly#73] opened 2015-10-21 15:22 UTC
Redirect Request Rule:
Url Matches: `/^(https?:\/\/)(www.)?youtube\.com\/embed\/(.*)$/ig`
Destination: `$1$2youtube.com/watch?v=$3`

All parameters are matched
Test 1: `http://www.youtube.com/embed/AXIPp6NUBi4`
Result 1: `http://www.youtube.com/watch?v=AXIPp6NUBi4`

Parameter `$2` is empty `$ -> %24`
Test 2: `http://youtube.com/embed/AXIPp6NUBi4`
Result 2: `http://`**%242**`youtube.com/watch?v=AXIPp6NUBi4`

**Comment by blunderboy** [comment] 2015-10-23 05:18
@offhub After checking the code, looks like this code is already handled. Please have a look at this piece of code https://github.com/blunderboy/requestly/blob/master/src/background/background.js#L145

    matches.forEach(function (matchValue, index) {
        // First match is the full string followed by parentheses/group values
        if (index === 0 || !matchValue) {    // See here if match value is empty we simply return 
          return;
        }

        // Replace all $index values in destinationUrl with the matched groups
        destinationUrl = destinationUrl.replace(new RegExp('[\$]' + index, 'g'), matchValue);
      });

But the issue is, when $2 is empty your destination url becomes `http://$2youtube.com/watch?v=AXIPpn6UNi4` and browser encodes $ to `%24` and thus you see that value.

I will fix this issue and I need to replace matchValue even if it is empty.

**Comment by blunderboy** [comment] 2015-10-23 05:38
@offhub I have fixed this issue and released the latest package on Chrome store. Fix should be available soon. Closing this issue. Thanks for notifying this.

**Closed by blunderboy** 2015-10-23 05:38 UTC
Labels: bug

**Comment by offhub** [comment] 2015-10-23 13:01
Thanks for the fix, @blunderboy
