### ISSUE TITLE
Press and hold F5 while requestly is enabled causes "pending" forever

### ISSUE THREAD

**Issue by nitech** [blunderboy/requestly#52] opened 2015-05-18 11:13 UTC
When I enable the requestly-extension (or any other header-modifying Chrome extension) and then press and hold the F5-key, after a little while the images on the site gets stuck in "pending" mode and remains so until I kill and restart the Chrome.exe process.

I am somewhat puzzled as to why this happens, and I wonder if you have had similar reports. Using Chrome 42. 

Check out this screencast to see the details of what is happening: http://youtu.be/ToTFfkYw-4s?hd=1

**Comment by nitech** [comment] 2015-05-18 11:31
I did some testing with Fiddler and FiddlerScript, and when I modify the header via Fiddler, everything works fine.

**Comment by blunderboy** [comment] 2015-05-18 12:22
@nitech Wow!! Cool testing stuff you have done..I have recently pushed an update (Issue #52) today morning itself to Requestly which should be available to you by now. Can you please recheck if this still happens to you ?

Anyways, I tried to create a very simple page to reproduce this
http://blunderboy.github.io/sandbox/requestly_52.html

I kept on pressing F5 like 7-8 times but image load fine for me.
Can you tell me the URL of the page which you used in your youtube Video ?

**Comment by nitech** [comment] 2015-05-18 13:34
Hi :-) The site is unfortunately not on the net. 

Try running a localhost nodejs or http-server instance in order to get quick response and then press and hold F5 continuously until the bug appears. 

I will do some testing tomorrow on a similar setup. Perhaps the issue is further linked with the file type, document type or similar.

**Comment by blunderboy** [comment] 2015-05-18 14:17
Hi Simon,

I created python http server in my git directory where the above mentioned
page was there.
I tried opening http://localhost:7070/sandbox/requestly_52.html and
refreshed the page with F5 multiple times but page loaded pretty much for
me again.

Yeah, I guess the issue may be linked to the file type/server. That's why I
asked for your site instead.

-Sachin

**Comment by blunderboy** [comment] 2015-05-20 04:25
@nitech Do you think we can close this issue. Otherwise Please try to provide a reproducible setup..

**Comment by nitech** [comment] 2015-05-20 04:53
I will make a setup and test with the latest requestly today. Let's see what comes out of it

**Comment by nitech** [comment] 2015-05-20 05:47
Regarding http://blunderboy.github.io/sandbox/requestly_52.html, I believe the response time of a server on the internet is too slow to trigger what I believe is a bug in Chrome. I'll do some testing with a http-server locally.

**Comment by nitech** [comment] 2015-05-20 07:57
I've published a repository that should let you reproduce the bug: 
https://github.com/nitech/chrome-header-extension-bug

Follow this video to see how I configure Chrome and/or read the readme.md file at the repository
http://youtu.be/2GH7hCzkVUI?hd=1

**Comment by blunderboy** [comment] 2015-05-20 09:10
Simon, That's great.
I would look into it later today and if required I will open a bug on
Chrome Project or probably on my side as I see fit.

-Sachin

**Comment by nitech** [comment] 2015-05-20 09:15
Cool Sachin. I already filed an issue on the Chromium project. Waiting for it to be approved. I'll post a link here when it's live.

**Comment by blunderboy** [comment] 2015-05-20 10:15
Simon, I would suggest you to host your page on github (Use github Static
Pages). It would become really easy for anyone in Chromium project to
reproduce this issue.

[0]: https://pages.github.com/

-Sachin

**Comment by nitech** [comment] 2015-05-20 11:22
Thanks Sachin. It's now available at http://nitech.github.io/chrome-header-extension-bug/ -- however, I can't reproduce the bug when loading the site from that URL. It seems the web server must be able to respond quicker than github.io in order to trigger the bug. Try with http-server locally instead.

**Comment by blunderboy** [comment] 2015-05-20 11:55
Thanks Simon for the effort....This should be more useful information to
anybody who will be looking into this bug.

-Sachin

**Comment by nitech** [comment] 2015-05-21 09:28
The Chromium issue is locateed here: https://code.google.com/p/chromium/issues/detail?id=490027

**Comment by blunderboy** [comment] 2015-05-21 11:03
Thanks Simon..Let's see how is this issue fixed.
But really, do you need this bug fixed for some use case or you just
happened to find it randomly.

-Sachin

**Comment by nitech** [comment] 2015-05-21 11:12
We run a site that is connected to a local web server, and it uses a RabbitMQ server for pushing messages through SignalR to the client.

When SignalR pushes messages really quickly, they actually trigger the same bug as we are able to trigger by holding down F5.

Since the site is running on eight different touchscreens, during a whole day, we sometimes experience that all the screens lose their images.

So as you see this is not just simply for kicks, it is a real scenario.

**Comment by blunderboy** [comment] 2015-05-23 11:36
@nitech Yeah...I am sorry man!! I am no help here because it seems to be Chrome issue.
I am closing this issue as I do not think I can help here. Feel free to reopen it if you think I can help here anyhow.

**Closed by blunderboy** 2015-05-23 11:36 UTC

**Comment by nitech** [comment] 2015-05-23 12:19
No problem :-) I agree that it is a Chrome issue.
